# Generated by Django 2.2 on 2019-06-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('V', 'Vitamins'), ('C', 'Calcium')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='turtle',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
