# Generated by Django 2.2 on 2019-06-16 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_turtle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turtle',
            name='user',
        ),
    ]
